name: genlogs_weather_dbt

profile: genlogs_weather_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  genlogs_weather_dbt:

    bronze:
      +schema: bronze
      +materialized: view

    silver:
      +schema: silver
      +materialized: view

    gold:
      +schema: gold
      +materialized: incremental
