create or replace TABLE GENLOGS.RAW.WEATHER_HOURLY_RAW (
	LOCATION_NAME VARCHAR(16777216),
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	FORECAST_HOUR TIMESTAMP_NTZ(9),
	TEMPERATURE_2M FLOAT,
	PRECIPITATION FLOAT,
	PRECIPITATION_PROBABILITY FLOAT,
	IS_DAY BOOLEAN,
	INGESTED_AT TIMESTAMP_NTZ(9),
	SOURCE VARCHAR(16777216)
);